### ISSUE TITLE
Pure Pursuit implementation (exists?)

### ISSUE THREAD

**Issue by IonyM** [winstxnhdw/KinematicBicycleModel#1]
Hi W!

I'm looking to evaluate the pure-pursuit algorithm in your simulator. 
Do you have already an implementation?
If not, I'd be happy to propose my solution and to hear recommendations. Specially on making the lookahead distance dynamic, maybe speed dependant as proposed here:
![PurePursuit](https://user-images.githubusercontent.com/63537843/125335967-d3cbb480-e355-11eb-9a36-bc15bfc85941.png)
[taken from https://www.coursera.org/learn/intro-self-driving-cars]

cheers!

**Comment by winstxnhdw** [comment]
Hello,

The animation here uses the [Stanley method](https://github.com/winstxnhdw/FullStanleyController) for its controller. As for the reason I didn't implement a Pure Pursuit controller instead is because tests done by others have shown that a Pure Pursuit controller is inferior for minimising crosstrack error and discomfort in most cases.
